const PALETTE = {
  BLACK: '#444',
  WHITE: '#fff',
  BLUE: 'cornflowerblue',
  BROWN: 'sandybrown',
  SHADOW_BROWN: '#cc8a50',
  BRIGHT_BROWN: '#f5ceab',
  RED: 'crimson',
  DARK: 'dimgray',
  GRAY: '#d0d0d0',
  LIGHTGRAY: '#f0f0f0',
  SILVER: '#f6f6f6',
  SMOKE: '#fcfcfc'
};

export const THEME = {
  MAIN: PALETTE.BROWN,
  MAIN_DARK: PALETTE.SHADOW_BROWN,
  MAIN_LIGHT: PALETTE.BRIGHT_BROWN,
  CLEAR: PALETTE.WHITE,
  SMOKE: PALETTE.SMOKE,
  DARKSMOKE: PALETTE.SILVER,
  SHADOW: PALETTE.LIGHTGRAY,
  DARK: PALETTE.DARK,
  BLACK: PALETTE.BLACK,
  DISABLED: PALETTE.GRAY,
  WARNING: PALETTE.RED
};
